### ISSUE TITLE
Fix DELETE in frontend

### ISSUE THREAD

**Issue by geekwise-estefania-flores** [geekwise-estefania-flores/django-drf-react-todo#2]
- Access to XMLHttpRequest at 'https://8000-a4e6c3d4-5f88-4ee9-a45e-662be3d3372e.ws-us02.gitpod.io/todos/2' from origin 'https://3000-a4e6c3d4-5f88-4ee9-a45e-662be3d3372e.ws-us02.gitpod.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
createError.js:17 

- Uncaught (in promise) Error: Network Error
    at createError (createError.js:17)
    at XMLHttpRequest.handleError (xhr.js:80)

**Comment by geekwise-estefania-flores** [comment]
[file:///Users/stefi/Desktop/Screen%20Shot%202019-12-03%20at%204.40.15%20PM.png](url)

**Comment by climateamante** [comment]
![delete example](https://user-images.githubusercontent.com/29623356/70102630-8e79c980-15ed-11ea-91d6-9ba93f1eebd6.gif)
@geekwise-estefania-flores can you link to the file where the request is made?

**Comment by geekwise-estefania-flores** [comment]
![image](https://user-images.githubusercontent.com/57374136/70102744-e7496200-15ed-11ea-92f1-50fbe5909dc1.png)

**Comment by geekwise-estefania-flores** [comment]
@climateamante https://github.com/geekwise-estefania-flores/django-drf-react-todo/blob/frontend/app/frontend/src/App.js
